'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('gw-token')||'',runs=[],current=null,report=null,events=[],offset=null,tab='overview';const checked=new Set();
const fragment=new URLSearchParams(location.hash.slice(1));if(fragment.has('token')){token=fragment.get('token');sessionStorage.setItem('gw-token',token);history.replaceState(null,'',location.pathname);}
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const pretty=v=>JSON.stringify(v,null,2);const num=v=>v===null||v===undefined?'Unknown':Number(v).toLocaleString();
const duration=v=>v===null||v===undefined?'In progress':v<60?v.toFixed(1)+'s':(v/60).toFixed(1)+'m';
async function api(path){const r=await fetch(path,{headers:{Authorization:'Bearer '+token}});if(r.status===401){$('auth').hidden=false;throw new Error('Local token required');}if(!r.ok)throw new Error('Data unavailable ('+r.status+')');return r.json();}
function connection(text,error=false){$('connection').textContent=text;$('connection').className=error?'status-approve':'muted';}
function table(headers,rows){const w=el('div',undefined,'table-wrap'),t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const b=el('tbody');for(const row of rows){const tr=el('tr');for(const v of row){const td=el('td');td.append(v instanceof Node?v:document.createTextNode(String(v)));tr.append(td);}b.append(tr);}t.append(b);w.append(t);return w;}
function renderRuns(){const q=$('filter').value.toLowerCase();$('runs').replaceChildren();const visible=runs.filter(r=>[r.name,r.manifest.harness,r.manifest.model].join(' ').toLowerCase().includes(q));for(const r of visible){const row=el('div',undefined,'run-row'+(r.id===current?' selected':''));const check=el('input');check.type='checkbox';check.checked=checked.has(r.id);check.setAttribute('aria-label','Compare '+r.name);check.onchange=()=>{if(check.checked&&checked.size>=10){check.checked=false;connection('Compare at most ten runs',true);return;}check.checked?checked.add(r.id):checked.delete(r.id);$('compare').disabled=checked.size<2;$('compare').textContent='Compare ('+checked.size+')';};const button=el('button',undefined,'run-link');button.append(el('strong',r.name),el('small',r.manifest.harness+' · '+(r.manifest.model||'model not recorded')),el('small',r.manifest.mode+' · '+new Date(r.started_ns/1e6).toLocaleString()));button.onclick=()=>loadRun(r.id);row.append(check,button);$('runs').append(row);}if(!visible.length)$('runs').append(el('p','No matching recorded runs.','muted'));}
async function refresh(){try{runs=await api('/api/runs');$('auth').hidden=true;renderRuns();if(current)await loadRun(current,false);else if(runs.length)await loadRun(runs[0].id);connection('Updated '+new Date().toLocaleTimeString());}catch(e){connection(e.message+' · showing last loaded data',true);}}
async function loadRun(id,reset=true){try{report=await api('/api/report/'+encodeURIComponent(id));current=id;$('empty').hidden=true;$('run').hidden=false;$('comparison').hidden=true;if(reset){events=[];offset=0;}renderRuns();renderReport();if(reset||tab==='trace')await loadTimeline(reset);connection('Updated '+new Date().toLocaleTimeString());}catch(e){connection(e.message,true);}}
function renderReport(){const r=report.run;$('title').textContent=r.name;$('outcome').textContent=r.outcome;$('run-meta').textContent=r.manifest.harness+' / '+(r.manifest.model||'model not recorded')+' · '+r.manifest.mode+' · '+r.id.slice(0,12);$('coverage').textContent=report.intercepts+' recorded intercepts. '+report.missing_source_records+' missing source records. Usage is observed coverage; unknown does not mean zero.';
$('metrics').replaceChildren();for(const [label,value,note] of [['GW intercepts',num(report.intercepts),'Verdicts issued, not verified effects'],['Model turns',num(report.observed_model_turns),'Observed requests or assistant turns'],['Task elapsed',duration(report.elapsed_seconds),'Explicit start → finish, including pauses'],['Recorded cost',report.usage.cost_usd==null?'Unknown':'$'+report.usage.cost_usd.toFixed(4),'Reported amount; not subscription allocation']]){const m=el('div',undefined,'metric');m.append(el('span',label,'muted'),el('span',value,'value'),el('small',note));$('metrics').append(m);}
$('goals').replaceChildren(table(['Goal','Evaluation states','Signals'],Object.entries(report.goal_evaluations).map(([g,v])=>[g,Object.entries(v).filter(([k])=>!['advise','approve','deny'].includes(k)).map(([k,n])=>k+': '+n).join(', '),['advise','approve','deny'].filter(k=>v[k]).map(k=>k+': '+v[k]).join(', ')||'None'])));if(!Object.keys(report.goal_evaluations).length)$('goals').append(el('p','No goal evaluations recorded. Baseline runs do not call a drift classifier.','muted'));
$('tools').replaceChildren();for(const [k,v] of Object.entries(report.tools)){$('tools').append(el('div',k+' — '+v,'bar-row'));}if(!Object.keys(report.tools).length)$('tools').append(el('p','No classified tool observations.','muted'));
$('usage').replaceChildren(table(['Metric','Reported value','Records with value'],Object.entries(report.usage).map(([k,v])=>[k,num(v),report.usage_reporting_counts[k]||0])));$('usage').append(el('h3','Where the work ran'),table(['Model','Observed usage records','Input','Output','Reported cost'],Object.entries(report.usage_by_model||{}).map(([m,v])=>[m,num(v.records),num(v.usage.input_tokens),num(v.usage.output_tokens),v.usage.cost_usd==null?'Unknown':'$'+v.usage.cost_usd.toFixed(4)])),el('h3','Supervisor overhead'),table(['Measurement','Value'],[['Classifier requests',num(report.classifier_calls)],['Supervisor input tokens',num(report.supervisor_usage?.input_tokens)],['Supervisor output tokens',num(report.supervisor_usage?.output_tokens)],['Evaluation time (sum)',num(report.evaluation_overhead_ms)+' ms'],['Trace recording time (sum)',num(report.logging_overhead_ms)+' ms'],['Observed user turns',num(report.observed_user_turns)],['Explicit agent IDs',report.observed_agent_ids?.join(', ')||'Not recorded'],['Observed skill IDs',report.observed_skills?.join(', ')||'Not recorded']]));if(report.usage_ambiguities.length)$('usage').append(el('p','Overlapping usage sources were not summed. Inspect the manifest/report for chosen sources.','notice'));
$('cache').replaceChildren(table(['Cache outcome','Count'],Object.entries(report.context_cache)),el('h3','Context compilation'),table(['Measurement','Value'],Object.entries(report.context_compilation||{})));$('edges').replaceChildren();for(const edge of report.context_edges.slice(0,100))$('edges').append(el('div',edge.from+' → '+edge.to+' · '+edge.relation,'bar-row'));if(!report.context_edges.length)$('edges').append(el('p','No explicit context or parent relationships were recorded.','muted'));
$('learning-data').replaceChildren(table(['Lifecycle event','Count'],Object.entries(report.learning)));if(!Object.keys(report.learning).length)$('learning-data').append(el('p','No learning lifecycle events were recorded for this run.','muted'));
$('manifest-data').textContent=pretty({manifest:r.manifest,configuration:report.configuration,goal_outcomes:report.goal_outcomes,outcome:r.outcome,outcome_evidence:r.evidence,usage_sources:report.usage_sources,usage_ambiguities:report.usage_ambiguities,interpretation:report.interpretation});drawDrift(report.drift);}
function drawDrift(points){$('drift').replaceChildren();if(!points.length){$('drift').append(el('p','Alignment was not measured. No drift curve is inferred from an unscored run.','muted'));return;}const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 900 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Observed alignment deviation from zero to one over the recorded sequence. Higher values indicate more deviation, not proven task failure.');const nodes=[];const step=Math.max(1,Math.ceil(points.length/400)),p=points.filter((_,i)=>i%step===0||i===points.length-1);const line=(tag,attrs)=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;};for(const value of [0,.5,1]){const y=150-value*125;line('line',{x1:45,x2:875,y1:y,y2:y,class:'grid'});line('text',{x:12,y:y+4}).textContent=String(value);}const coords=p.map((x,i)=>[45+i/Math.max(1,p.length-1)*830,150-x.score*125]);line('polyline',{points:coords.map(x=>x.join(',')).join(' '),class:'curve'});p.forEach((x,i)=>{const c=line('circle',{cx:coords[i][0],cy:coords[i][1],r:4,class:['deny','approve'].includes(x.decision)?'point':'datum',tabindex:0,role:'button','aria-label':'Inspect alignment '+x.score+'; '+x.decision});c.onclick=()=>detail(x.event_id);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detail(x.event_id)}};const t=document.createElementNS(NS,'title');t.textContent=new Date(x.at_ns/1e6).toLocaleString()+' · '+x.score+' · '+x.decision;c.append(t);});$('drift').append(svg,el('p',points.length+' observations · '+(step>1?'sampled for display · ':'')+'amber markers: review/deny verdicts. Full values remain in the trace.','muted'));}
async function loadTimeline(reset=false){if(!current)return;if(reset){events=[];offset=0;}if(offset===null)return;const data=await api('/api/timeline/'+encodeURIComponent(current)+'?offset='+offset);events.push(...data.events);offset=data.next_offset;renderTimeline();}
function renderTimeline(){const kind=$('kind-filter').value;const visible=events.filter(e=>!kind||e.kind.startsWith(kind));$('timeline').replaceChildren(table(['Time','Kind','Operation / model','Decision / state','Inspect'],visible.map(e=>{const a=e.attributes,b=el('button','Open');b.onclick=()=>detail(e.id);return[new Date(e.start_ns/1e6).toLocaleTimeString(),e.kind,a.tool||a.model||a.operation||'—',a.decision||a.status||'recorded',b];})));$('more').hidden=offset===null;}
async function detail(id){try{const e=await api('/api/event/'+encodeURIComponent(id));const d=e.detail?.data,box=$('detail-content');box.replaceChildren(el('p',e.kind+' · '+e.id,'muted'));if(d?.audit){const cols=el('div',undefined,'detail-columns');for(const[label,v]of [['Agent proposed',d.audit.proposal],['GW directed',{decision:d.decision,reason:d.reason,advice:d.advice,route:d.inference?.plan}]]){const s=el('section');s.append(el('h3',label),el('pre',pretty(v)));cols.append(s);}box.append(cols,el('h3','Goal evaluations'),el('pre',pretty(d.audit.goals)));}else if(d)box.append(el('h3','Referenced source (read on demand)'),el('pre',pretty(d)));else box.append(el('p',e.detail?.status?'Source status: '+e.detail.status:'No underlying content was copied.','notice'));for(const linked of e.linked_sources||[]){const b=el('button','Open original agent record');b.onclick=()=>{$('detail').close();detail(linked);};box.append(b);}box.append(el('h3','Recorded metadata and provenance'),el('pre',pretty({attributes:e.attributes,source:e.source,start_ns:e.start_ns,end_ns:e.end_ns,parent_id:e.parent_id})));$('detail').showModal();}catch(e){connection(e.message,true);}}
$('filter').oninput=renderRuns;$('refresh').onclick=refresh;$('kind-filter').onchange=renderTimeline;$('more').onclick=()=>loadTimeline();$('close-detail').onclick=()=>$('detail').close();
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;for(const n of document.querySelectorAll('[data-tab]'))n.classList.toggle('active',n===b);for(const n of document.querySelectorAll('.panel'))n.hidden=n.id!==tab;if(tab==='trace'&&!events.length)loadTimeline(true);};
$('auth-form').onsubmit=e=>{e.preventDefault();token=$('token').value.trim();sessionStorage.setItem('gw-token',token);$('token').value='';refresh();};
$('compare').onclick=async()=>{try{const ids=[...checked].slice(0,10),data=await api('/api/compare?'+ids.map(id=>'id='+encodeURIComponent(id)).join('&'));$('run').hidden=true;$('comparison').hidden=false;const rows=[['Harness',r=>r.run.manifest.harness],['Model',r=>r.run.manifest.model||'Unknown'],['Mode',r=>r.run.manifest.mode],['Outcome',r=>r.run.outcome],['Elapsed',r=>duration(r.elapsed_seconds)],['Interceptions',r=>num(r.intercepts)],['Input tokens',r=>num(r.usage.input_tokens)],['Output tokens',r=>num(r.usage.output_tokens)],['Reported cost',r=>r.usage.cost_usd==null?'Unknown':'$'+r.usage.cost_usd.toFixed(4)]];$('comparison-data').replaceChildren(table(['Variable',...data.reports.map(r=>r.run.name)],rows.map(([n,f])=>[n,...data.reports.map(f)])),el('h2','Changed experiment variables'),el('pre',pretty(data.differences)));}catch(e){connection(e.message,true);}};$('close-compare').onclick=()=>{$('comparison').hidden=true;$('run').hidden=false;};
refresh();setInterval(()=>{if(!document.hidden&&!$('detail').open&&!$('comparison').hidden)return;if(!document.hidden&&!$('detail').open)refresh();},5000);
